// Box

export const BOX_ELEMENT_DELETED = 'SNC_WDS_MMC_BOX#ELEMENT_DELETED';

// Screen

export const SCREEN_LOADED = 'SNC_WDS_MMC_SCREEN#SCREEN_LOADED';
export const SCREEN_RESIZED = 'SNC_WDS_MMC_SCREEN#SCREEN_RESIZED';
export const SCREEN_DRAWING_STARTED = 'SNC_WDS_MMC_SCREEN#DRAWING_STARTED';
export const SCREEN_DRAWING_CONTINUED = 'SNC_WDS_MMC_SCREEN#DRAWING_CONTINUED';
export const SCREEN_DRAWING_ENDED = 'SNC_WDS_MMC_SCREEN#DRAWING_ENDED';
export const SCREEN_DRAWING_CANCELLED = 'SNC_WDS_MMC_SCREEN#DRAWING_CANCELLED';

export const SCREEN_ELEMENTS_UPDATED = 'SNC_WDS_MMC_SCREEN#ELEMENTS_UPDATED';
export const SCREEN_ELEMENT_DELETED = 'SNC_WDS_MMC_SCREEN#ELEMENT_DELETED';

// Device

export const DEVICE_IMAGE_LOADED = 'SNC_WDS_MMC_DEVICE#IMAGE_LOADED';
export const DEVICE_LOAD_COMPLETED = 'SNC_WDS_MMC_DEVICE#LOAD_COMPLETED';

export const DEVICE_KEY_RIGHT_PRESSED = 'SNC_WDS_MMC_DEVICE#KEY_RIGHT_PRESSED';
export const DEVICE_KEY_LEFT_PRESSED = 'SNC_WDS_MMC_DEVICE#KEY_LEFT_PRESSED';
export const DEVICE_KEY_ESCAPE_PRESSED = 'SNC_WDS_MMC_DEVICE#KEY_ESCAPE_PRESSED';

export const DEVICE_ELEMENTS_UPDATED = 'SNC_WDS_MMC_DEVICE#ELEMENTS_UPDATED';
export const DEVICE_ELEMENT_DELETED = 'SNC_WDS_MMC_DEVICE#ELEMENT_DELETED';

